# Generated by Django 5.2.17 on 2026-08-17 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_seed_subscription_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('card', 'Card'), ('upi', 'UPI')], default='card', max_length=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='upi_id_masked',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='payment',
            name='card_last4',
            field=models.CharField(blank=True, max_length=4),
        ),
    ]
