# Generated by Django 5.2.17 on 2026-08-07 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_seed_media_library'),
    ]

    operations = [
        migrations.CreateModel(
            name='CastMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(max_length=170, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='cast/photos/')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='MovieCast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('character', models.CharField(max_length=150)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('cast_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_credits', to='catalog.castmember')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cast_credits', to='catalog.movie')),
            ],
            options={
                'ordering': ('order', 'id'),
                'constraints': [models.UniqueConstraint(fields=('movie', 'cast_member'), name='unique_movie_cast_member')],
            },
        ),
    ]
