import { Download, FileClock, History, ReceiptText } from "lucide-react"
import type { ReactNode } from "react"
import { Link } from "react-router-dom"

import { Button } from "@/components/ui/button"
import { Card, CardContent, CardHeader } from "@/components/ui/card"
import { downloadCsv } from "@/features/reports/csv"
import type { ReportsOverview } from "@/features/reports/types"

function TableCard({ title, description, icon, onExport, testId, children }: { title: string; description: string; icon: ReactNode; onExport: () => void; testId: string; children: ReactNode }) {
  return <Card data-testid={testId}><CardHeader className="flex-row items-center justify-between gap-4"><div className="flex items-center gap-3"><span className="flex size-10 items-center justify-center rounded-xl bg-primary/15 text-indigo-400">{icon}</span><div><h2 className="font-bold">{title}</h2><p className="text-sm text-muted-foreground">{description}</p></div></div><Button variant="secondary" size="sm" onClick={onExport} data-testid={`${testId}-export`}><Download />Export CSV</Button></CardHeader><CardContent className="overflow-x-auto p-0">{children}</CardContent></Card>
}

const th = "whitespace-nowrap border-b px-6 py-3 text-left text-xs font-bold uppercase tracking-wider text-muted-foreground"
const td = "whitespace-nowrap border-b border-border/70 px-6 py-4 text-sm last:border-b-0"
const emptyRow = (columns: number) => <tr><td colSpan={columns} className="px-6 py-12 text-center text-sm text-muted-foreground">No records match the selected filters.</td></tr>

export function ReportTables({ data }: { data: ReportsOverview }) {
  const exportHistory = () => downloadCsv("streamcheck-watch-history.csv", ["Title", "Category", "Progress seconds", "Completed", "First watched", "Last watched"], data.watch_history.map((item) => [item.movie.title, item.movie.category.name, item.progress_seconds, item.completed ? "Yes" : "No", item.first_watched_at, item.last_watched_at]))
  const exportActivity = () => downloadCsv("streamcheck-activity.csv", ["Type", "Title", "Description", "Created"], data.activity.map((item) => [item.event_type, item.title, item.description, item.created_at]))
  const exportSubscriptions = () => downloadCsv("streamcheck-subscriptions.csv", ["Plan", "Status", "Amount", "Currency", "Starts", "Ends", "Auto renew"], data.subscriptions.map((item) => [item.plan.name, item.status, item.amount, item.currency, item.starts_at, item.ends_at, item.auto_renew ? "Yes" : "No"]))
  return <div className="space-y-5" data-testid="report-tables">
    <TableCard title="Watch history" description={`${data.watch_history.length} viewing records`} icon={<History className="size-5" />} onExport={exportHistory} testId="watch-history-report-table"><table className="w-full min-w-[760px]"><thead><tr><th className={th}>Title</th><th className={th}>Category</th><th className={th}>Progress</th><th className={th}>Status</th><th className={th}>Last watched</th></tr></thead><tbody>{data.watch_history.length ? data.watch_history.map((item) => <tr key={item.id} className="transition-colors hover:bg-secondary/30"><td className={td}><Link to={`/movies/${item.movie.slug}`} className="font-semibold hover:text-indigo-400">{item.movie.title}</Link></td><td className={td}>{item.movie.category.name}</td><td className={td}>{Math.floor(item.progress_seconds / 60)}m {item.progress_seconds % 60}s</td><td className={td}><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${item.completed ? "bg-success/15 text-success" : "bg-primary/15 text-indigo-300"}`}>{item.completed ? "Completed" : "In progress"}</span></td><td className={td}>{new Date(item.last_watched_at).toLocaleString()}</td></tr>) : emptyRow(5)}</tbody></table></TableCard>
    <TableCard title="Activity" description={`${data.activity.length} account events`} icon={<FileClock className="size-5" />} onExport={exportActivity} testId="activity-report-table"><table className="w-full min-w-[760px]"><thead><tr><th className={th}>Type</th><th className={th}>Event</th><th className={th}>Description</th><th className={th}>Date</th></tr></thead><tbody>{data.activity.length ? data.activity.map((item) => <tr key={item.id} className="transition-colors hover:bg-secondary/30"><td className={td}><span className="rounded-full bg-secondary px-2.5 py-1 text-xs font-semibold capitalize">{item.event_type}</span></td><td className={`${td} font-semibold`}>{item.title}</td><td className={`${td} max-w-sm truncate text-muted-foreground`}>{item.description}</td><td className={td}>{new Date(item.created_at).toLocaleString()}</td></tr>) : emptyRow(4)}</tbody></table></TableCard>
    <TableCard title="Subscriptions" description={`${data.subscriptions.length} subscription records`} icon={<ReceiptText className="size-5" />} onExport={exportSubscriptions} testId="subscription-report-table"><table className="w-full min-w-[760px]"><thead><tr><th className={th}>Plan</th><th className={th}>Status</th><th className={th}>Amount</th><th className={th}>Started</th><th className={th}>Ends</th><th className={th}>Auto renew</th></tr></thead><tbody>{data.subscriptions.length ? data.subscriptions.map((item) => <tr key={item.id} className="transition-colors hover:bg-secondary/30"><td className={`${td} font-semibold`}>{item.plan.name}</td><td className={td}><span className={`rounded-full px-2.5 py-1 text-xs font-semibold capitalize ${item.status === "active" ? "bg-success/15 text-success" : "bg-secondary text-muted-foreground"}`}>{item.status}</span></td><td className={td}>{item.currency} {Number(item.amount).toFixed(2)}</td><td className={td}>{new Date(item.starts_at).toLocaleDateString()}</td><td className={td}>{new Date(item.ends_at).toLocaleDateString()}</td><td className={td}>{item.auto_renew ? "Yes" : "No"}</td></tr>) : emptyRow(6)}</tbody></table></TableCard>
  </div>
}
